language: node_js
node_js:
  - "6"
  - "7"
sudo: required
dist: trusty
cache:
  apt: true
addons:
  apt:
    packages:
    - libzmq3-dev
script: "make travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
